### ISSUE TITLE
Maximum response of GET request only 128 bytes?

### ISSUE THREAD

**Issue by ankgt** [carrascoacd/ArduinoSIM800L#11]
Firstly thanks a lot for your library. I modified it slightly to use HardwareSerial on my ESP32 and it works very well for post requests. I just had to couple of observations:

1. My API endpoint returns a 201 (Created) for a successful new POST request. I think many API's do that. The current library does not detect this and expects a 200, and returns an error. I manually changed this in the post() function and now POST works perfectly. 

2. The get() function creates a "Stack smashing protect failure!" fault on my ESP32 and crashes it. I think it has something to do with the buffer size in the readResponse() method being only 128 bytes. My GET response is about 600 bytes. Is there any reason why the buffer is so small? Is it safe for me to increase it, or is there any other associated problem I should be careful of?

Thanks!

**Comment by carrascoacd** [comment]
Hi! 

- I've just improved the library today to support 2XX response codes both, in post and get requests, as I needed it also and is a basic feature, so you can pull the update if you want.
- The buffer size is 128 bytes as I'm using Arduino Nano with a 2KB SRAM, so the library try to be optimised to be used in small boards. Finally, its safe to increase the buffer size if you need it.
A new feature to have a configurable buffer size could be nice to support bigger responses.

Thanks for your feedback :)

**Comment by carrascoacd** [comment]
Support for 2XX responses in https://github.com/carrascoacd/ArduinoSIM800L/commit/92d3c409f7556958c687584ca141342cf698b646. New issue related to configurable buffer size here #12

**Comment by ankgt** [comment]
Thanks very much. It works great now!

**Comment by Musigwa-zz** [comment]
Hello guys!  i want to use this library first for get request but i'm getting an empty response and don't know the reason why

the response that i'm getting on the terminal are the following

AT

OK
AT+CREG?

+CREG: 0,1

OK
AT+SAPBR=3,1,"Contype","GPRS"

OK
AT+SAPBR=3,1,"APN","web.mtn4g.rw"

OK
AT+SAPBR=2,1

+SAPBR: 1,3,"0.0.0.0"

OK
AT+SAPBR=1,1

OK
AT+SAPBR=2,1

+SAPBR: 1,1,"10.20.220.146"

OK
AT+HTTPINIT

OK
AT+HTTPPARA="CID",1

OK
AT+HTTPPARA="URL","https://fyincaserver.herokuapp.com/"

OK
AT+HTTPSSL=1

OK
AT+HTTPPARA="CONTENT","application/json"

OK
AT+HTTPACTION=0

OK
response:

AT+SAPBR=0,1

+HTTPACTION: 0,601,0

OK

would anyone help on this issue??
thanks in advance

**Comment by Musigwa-zz** [comment]
I'm using arduino nano, and GSM sim 800L,  the mini RED colored module.
My server returns the 200 for successful get request at first and returns 304 for the next requests.
and it accept json data as it is a node server

**Comment by carrascoacd** [comment]
Hi!

Do you have PIN in your SIM card?
Are you using a LiPo battery?
