### ISSUE TITLE
Usr & pwd

### ISSUE THREAD

**Issue by julioBesse** [carrascoacd/ArduinoSIM800L#13]
Where should I  put my User and Password for APN autentication?

**Comment by carrascoacd** [comment]
Is not supported right now. Have you tried the lib without it?

If you are playing with AT cmd try:
AT+CSTT= "APN", "USER", "PWD"

**Comment by julioBesse** [comment]
Hola Antonio,
Gracias por tu respuesta. Modifiqué http.h y http.cpp para que reciba 3
parámetros de entrada y quedó funcionando ok.
Saludos.

**Comment by carrascoacd** [comment]
Ok! eres bienvenido si quieres hacer una contribución con tu mejora 👍
