### ISSUE TITLE
Variable in payload

### ISSUE THREAD

**Issue by MateuszManaj** [carrascoacd/ArduinoSIM800L#14]
Hi there,
How to add (in proper way) a variable (concat) to this json payload ?
Result result = http.post("your.api.com", "{\"date\":\"12345678\"}", response);

thank you in advance
Matthew

**Comment by carrascoacd** [comment]
Just check this example: https://github.com/carrascoacd/ArduinoSIM800L/blob/master/HttpExample/HttpExample.ino#L53

It is based on `sprintf` 
https://www.tutorialspoint.com/c_standard_library/c_function_sprintf.htm
