### ISSUE TITLE
Hi,what is the 'response' mean in your code?And how can I do to use this lib to exchange the information with this tinywebdb, http://tinywebdb.appinventor.mit.edu

### ISSUE THREAD

**Issue by ZacLing** [carrascoacd/ArduinoSIM800L#15]
Hi,what is the 'response' mean in your code?And how can I do to use this lib to exchange the information with this tinywebdb, http://tinywebdb.appinventor.mit.edu.
Thank you very much

**Comment by jakobkhom** [comment]
When you send a post/get request to a http server it **responds** with a text, which you can use to e.g. check if the sent data is correct, or to receive json data, etc.

**Comment by carrascoacd** [comment]
https://code.tutsplus.com/tutorials/http-the-protocol-every-web-developer-must-know-part-1--net-31177
