### ISSUE TITLE
APN

### ISSUE THREAD

**Issue by MendynN** [carrascoacd/ArduinoSIM800L#17]
Hi,

I set http.configureBearer to my mobile service provider APN, but I still don't succeed to do the REST request, the code fail in the next line:

`http.configureBearer("my.mobile.service.provider.apn"); `

Can you help?

Thanks

**Comment by carrascoacd** [comment]
I need more information. Post your error trace so I can see what happens.

**Comment by jonathangaldino** [comment]
It's possible to add APN User and APN Password as well? Some of APNs here on Brazil needs a login.

**Comment by carrascoacd** [comment]
The library does not support it yet.
You should disable the PIN code to use it.

**Comment by jonathangaldino** [comment]
Yep. I did that and worked very well. Thanks one more time.
