### ISSUE TITLE
RSTPin isn't working

### ISSUE THREAD

**Issue by jonathangaldino** [carrascoacd/ArduinoSIM800L#18]
When should the library reset the GPS?
I'm having issues with the GPS getting stuck sometimes and the arduino stops working.
It is getting stuck when setting AT+SAPBR=2,1,"IP ADDRESS".

```
OK
AT

OK
AT+CREG?

+CREG: 0,1

OK
AT+SAPBR=3,1,"Contype","GPRS"

OK
AT+SAPBR=3,1,"APN","timbrasil.br"

OK
AT+SAPBR=2,1

+SAPBR: 1,3,"0.0.0.0"

OK
AT+SAPBR=1,1

OK
AT+SAPBR=2,1

+SAPBR: 1,1,"100.69.91.245"

OK

```

**Comment by JohnzBallad** [comment]
`asdasd
asdaddsssss
`

**Comment by carrascoacd** [comment]
The library does not implement anything related to GPS.
