### ISSUE TITLE
AT+HTTPINIT   -> ERROR

### ISSUE THREAD

**Issue by farsajik** [carrascoacd/ArduinoSIM800L#19]

**Comment by ostaquet** [comment]
Hi @farsajik,
Did the error appear in each loop or only in the first one?
It is strange that the HTTPINIT generated an ERROR but the rest of the communication seems to work according to your logs.
According to the specs, the error should be an error related to mobile equipment functionality.
The output of HTTPINIT in ERROR should be something like `+CME ERROR: <err>`. This log will help to diagnose the issue.
KR,
Olivier

**Comment by farsajik** [comment]
Thank you for reply.it is working now. can i send receive STRINGS  not JSon with this library?
