### ISSUE TITLE
While(1)

### ISSUE THREAD

**Issue by farsajik** [carrascoacd/ArduinoSIM800L#21]
Hi.when sim800l is off arduino freezes when sends data to sim800l.becouse without respond from sim800l it stucks inside while(1) loop.how to solve this problem.how to firstly check is sim800l attached then send data to module.thanks

**Comment by carrascoacd** [comment]
You can use the method
sendATTest()

For example:

if(TRUE == http.sendATTest()){
# working
}else{
# sim800l dead
}

**Comment by farsajik** [comment]
thanks
