### ISSUE TITLE
read battery voltage

### ISSUE THREAD

**Issue by jaka87** [carrascoacd/ArduinoSIM800L#22]
Hi there. Love the library. I noticed there is function to get the battery voltage but cant get it working.

```
char *batt;
batt=http.readVoltage(voltage);
```

gets me a 
`void value not ignored as it ought to be
`
how does one use it in order to get battery percentage ?

**Comment by carrascoacd** [comment]
Hi thanks!

Try this:

char voltae[64];
http.readVoltage(voltage);

**Comment by carrascoacd** [comment]
Hi! Thanks

Try this:

```
char voltage[64];
http.readVoltage(voltage);
