### ISSUE TITLE
Imei

### ISSUE THREAD

**Issue by farsajik** [carrascoacd/ArduinoSIM800L#24]
hi friend.for my project i need Imei  each device.I add function to return imei string.how can i get only imei numbers?.thanks

> `String HTTP::getImei(){
>   char buffer[64];
>   cleanBuffer(buffer, sizeof(buffer));
>   
>   sendCmd("AT+GSN\r\n");
>     
>   if (readBuffer(buffer, sizeof(buffer)) == TRUE){
>       String str(buffer);
>       return str;     
>   }
> }`

in my loop   `Serial.println(http.getImei()); `
in the terminal i am getting

> `AT+GSN
> 
> 866262031290909
> 
> OK
> 

`
how to get numbers only?thank you

**Comment by carrascoacd** [comment]
Hi, check out this method where I parse a JSON response `parseJSONResponse`
