### ISSUE TITLE
fast post request

### ISSUE THREAD

**Issue by farsajik** [carrascoacd/ArduinoSIM800L#37]
hi friend.thank you for this library.i need send as fast as possibly  POST request  for car tracking.i dont need download data from server.how can i do this?how can i simpilify this part of code?thanks

 `Result HTTP::post(const char *uri, const char *body, char *response) {
  Result result = setHTTPSession(uri);
  char httpData[32];
  unsigned int delayToDownload = 10000;
  sprintf(httpData, HTTP_DATA, strlen(body), 10000);
  if (sendCmdAndWaitForResp(httpData, DOWNLOAD, 2000) == FALSE){
    result = ERROR_HTTP_DATA;
  }

  purgeSerial();
  sendCmd(body);

  if (sendCmdAndWaitForResp(HTTP_POST, HTTP_2XX, delayToDownload) == TRUE) {
    sendCmd(HTTP_READ);
    readResponse(response);
    result = SUCCESS;
  }
  else {
    result = ERROR_HTTP_POST;
  }

  return result;
}`

**Comment by carrascoacd** [comment]
Hi!

Try reducing the `delayToDownload` value.
